[package]
name = "exchange_prototype"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
rust_decimal = "1.15.0"
rand = "0.8.4"
rand_chacha = "0.3.1"
json = "0.12.4"